// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asynchronousAPI.Data;

#nullable disable

namespace asynchronousAPI.Migrations
{
    [DbContext(typeof(SampleDbContext))]
    [Migration("20220513081021_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("asynchronousAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Product 1 description",
                            Name = "Product 1",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Product 2 description",
                            Name = "Product 2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Product 3 description",
                            Name = "Product 3",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Product 4 description",
                            Name = "Product 4",
                            Price = 400m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Product 5 description",
                            Name = "Product 5",
                            Price = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
